// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: copyfrom.go

package pgen

import (
	"context"
)

// iteratorForCreateGamePlayers implements pgx.CopyFromSource.
type iteratorForCreateGamePlayers struct {
	rows                 []CreateGamePlayersParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateGamePlayers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateGamePlayers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].GameID,
		r.rows[0].PlayerID,
	}, nil
}

func (r iteratorForCreateGamePlayers) Err() error {
	return nil
}

func (q *Queries) CreateGamePlayers(ctx context.Context, arg []CreateGamePlayersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"game_player"}, []string{"game_id", "player_id"}, &iteratorForCreateGamePlayers{rows: arg})
}
