// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: player.sql

package pgen

import (
	"context"
)

const addPlayer = `-- name: AddPlayer :exec
INSERT INTO player (username, password) VALUES ($1, $2)
`

type AddPlayerParams struct {
	Username string
	Password string
}

func (q *Queries) AddPlayer(ctx context.Context, arg AddPlayerParams) error {
	_, err := q.db.Exec(ctx, addPlayer, arg.Username, arg.Password)
	return err
}

const fetchPlayerByUsername = `-- name: FetchPlayerByUsername :one
SELECT id, username, password FROM player WHERE username = $1
`

func (q *Queries) FetchPlayerByUsername(ctx context.Context, username string) (Player, error) {
	row := q.db.QueryRow(ctx, fetchPlayerByUsername, username)
	var i Player
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}

const fetchPlayersByUsername = `-- name: FetchPlayersByUsername :many
SELECT id, username FROM player WHERE username = ANY($1::varchar[])
`

type FetchPlayersByUsernameRow struct {
	ID       int32
	Username string
}

func (q *Queries) FetchPlayersByUsername(ctx context.Context, usernames []string) ([]FetchPlayersByUsernameRow, error) {
	rows, err := q.db.Query(ctx, fetchPlayersByUsername, usernames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchPlayersByUsernameRow
	for rows.Next() {
		var i FetchPlayersByUsernameRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
